### ISSUE TITLE
installation fails because PostMessage_hsc_make.exe is flagged as malware

### ISSUE THREAD

**Issue by ptillemans** [haskell/win32#122]
## Steps to Reproduce (for bugs)

1.  install kaspersky total security
2.  run 'stack install Win32'
3.  Kaspersky blocks the execution of PostMessage_hsc_make.exe
4.  build fails with 
```
--  While building custom Setup.hs for package Win32-2.5.4.1 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.2.0.1_ghc-8.4.4.exe --builddir=.stack-work\dist\7d103d30 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Users\pti\playpen\spago\.stack-work\logs\Win32-2.5.4.1.log

    Configuring Win32-2.5.4.1...
    Preprocessing library for Win32-2.5.4.1..
    hsc2hs.exe: .stack-work\dist\7d103d30\build\Graphics\Win32\Window\PostMessage_hsc_make.exe: runProcess: permission denied (Permission denied)
```

this is the log of kaspersky

[trojan.txt](https://github.com/haskell/win32/files/2775896/trojan.txt)

## Your Environment

* Version used:
* Operating System and version: Windows 10 Pro

**Comment by ptillemans** [comment]
Probably a false positive, just erring on the side of caution.

**Comment by Mistuke** [comment]
Kaspersky's heuristics flag a lot of Haskell programs because the way haskell programs are executed. Win32 does not ship any binaries and this one is created locally by hsc2hs to generate the source code.

So yes this is a false positive, if it was a virus it would have had to have gotten infected directly after the program was made on your computer.
