### ISSUE TITLE
Incorrect types break 64 bit

### ISSUE THREAD

**Issue by csheanz** [haskell/win32#53]
The following types in System.Win32.Types are the wrong size on 64 bit Windows:

    type UINT_PTR = Word
    type ATOM          = UINT
    type WPARAM        = UINT
    type LPARAM        = LONG
    type LRESULT       = LONG
    type SIZE_T = DWORD

Propose adding `LONG_PTR`:

    type LONG_PTR = CIntPtr

and changing to:

    type UINT_PTR = CUIntPtr
    type ATOM          = WORD
    type WPARAM        = UINT_PTR
    type LPARAM        = LONG_PTR
    type LRESULT       = LONG_PTR
    type SIZE_T = CSize

**Comment by Mistuke** [comment]
Hi thanks for the report,

`ATOM` I agree is incorrect, that should indeed be a `short` and not a `UINT`.
`WPARAM` , `LPARAM` and `LRESULT`  I agree also
`SIZE_T` I'm a bit weary about causing confusions, because officially the standard only says it's `at least 16 bit`. So I would instead just define `ULONG_PTR = CUIntPtr` and use that instead. Since `SIZE_T` predates `size_t` anyway.

For reference, types are at https://msdn.microsoft.com/en-gb/library/windows/desktop/aa383751(v=vs.85).aspx
and https://msdn.microsoft.com/en-us/library/s3f49ktz.aspx.
